### ISSUE TITLE
BTP service instance name length

### ISSUE THREAD

**Issue by nimble-123** [lemaiwo/FioriMigration2CFTool#1]
Hi Wouter,

wonderful tool. Recently i encountered an issue with `service-name` length while deploying a MTA to BTP. If the defined `service-name` exceeds 49 characters it gets truncated with some hash-looking values and the deployment fails due to not resolvable dependencies.

Imagine the `reponame` would be something very long than the generated `service-name` would be very long as well. I do not have a generic solution for this but shrinking the `service-name` to max 49 characters should just do the trick. At least this is what i do when modelling the MTA descriptor ;)

Maybe you have a better solution or some sort of logic to tackle this. 

```yaml
- name: {{reponame}}-repo-host
  type: org.cloudfoundry.managed-service
  parameters:
    service: html5-apps-repo
    service-name: {{reponame}}-html5-srv <<<<<<<<<<<<<<<<<<
    service-plan: app-host
```
